/**
 * Root controller — a bare "hello world" GET / route generated by `nest new`.
 * Kept as a cheap liveness check (curl / uptime monitor) with no auth needed;
 * marked `@Public()` so the global JwtAuthGuard doesn't reject anonymous
 * callers hitting it. Not part of the domain API surface.
 */
import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';
import { Public } from './common/decorators/public.decorator';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Public()
  @Get()
  getHello(): string {
    return this.appService.getHello();
  }
}
